(cl:defpackage hello_pkg-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "PARAMACTION"
   "<PARAMACTION-REQUEST>"
   "PARAMACTION-REQUEST"
   "<PARAMACTION-RESPONSE>"
   "PARAMACTION-RESPONSE"
  ))

