// Generated by gencpp from file hello_pkg/ParamAction.msg
// DO NOT EDIT!


#ifndef HELLO_PKG_MESSAGE_PARAMACTION_H
#define HELLO_PKG_MESSAGE_PARAMACTION_H

#include <ros/service_traits.h>


#include <hello_pkg/ParamActionRequest.h>
#include <hello_pkg/ParamActionResponse.h>


namespace hello_pkg
{

struct ParamAction
{

typedef ParamActionRequest Request;
typedef ParamActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamAction
} // namespace hello_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hello_pkg::ParamAction > {
  static const char* value()
  {
    return "945ecb72549f28b95525ed9d393f5e1c";
  }

  static const char* value(const ::hello_pkg::ParamAction&) { return value(); }
};

template<>
struct DataType< ::hello_pkg::ParamAction > {
  static const char* value()
  {
    return "hello_pkg/ParamAction";
  }

  static const char* value(const ::hello_pkg::ParamAction&) { return value(); }
};


// service_traits::MD5Sum< ::hello_pkg::ParamActionRequest> should match
// service_traits::MD5Sum< ::hello_pkg::ParamAction >
template<>
struct MD5Sum< ::hello_pkg::ParamActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hello_pkg::ParamAction >::value();
  }
  static const char* value(const ::hello_pkg::ParamActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_pkg::ParamActionRequest> should match
// service_traits::DataType< ::hello_pkg::ParamAction >
template<>
struct DataType< ::hello_pkg::ParamActionRequest>
{
  static const char* value()
  {
    return DataType< ::hello_pkg::ParamAction >::value();
  }
  static const char* value(const ::hello_pkg::ParamActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hello_pkg::ParamActionResponse> should match
// service_traits::MD5Sum< ::hello_pkg::ParamAction >
template<>
struct MD5Sum< ::hello_pkg::ParamActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hello_pkg::ParamAction >::value();
  }
  static const char* value(const ::hello_pkg::ParamActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_pkg::ParamActionResponse> should match
// service_traits::DataType< ::hello_pkg::ParamAction >
template<>
struct DataType< ::hello_pkg::ParamActionResponse>
{
  static const char* value()
  {
    return DataType< ::hello_pkg::ParamAction >::value();
  }
  static const char* value(const ::hello_pkg::ParamActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HELLO_PKG_MESSAGE_PARAMACTION_H
