// Generated by gencpp from file hello_pkg/ParamActionResponse.msg
// DO NOT EDIT!


#ifndef HELLO_PKG_MESSAGE_PARAMACTIONRESPONSE_H
#define HELLO_PKG_MESSAGE_PARAMACTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_pkg
{
template <class ContainerAllocator>
struct ParamActionResponse_
{
  typedef ParamActionResponse_<ContainerAllocator> Type;

  ParamActionResponse_()
    : success(false)  {
    }
  ParamActionResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::hello_pkg::ParamActionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_pkg::ParamActionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ParamActionResponse_

typedef ::hello_pkg::ParamActionResponse_<std::allocator<void> > ParamActionResponse;

typedef boost::shared_ptr< ::hello_pkg::ParamActionResponse > ParamActionResponsePtr;
typedef boost::shared_ptr< ::hello_pkg::ParamActionResponse const> ParamActionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_pkg::ParamActionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_pkg::ParamActionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hello_pkg::ParamActionResponse_<ContainerAllocator1> & lhs, const ::hello_pkg::ParamActionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hello_pkg::ParamActionResponse_<ContainerAllocator1> & lhs, const ::hello_pkg::ParamActionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hello_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hello_pkg::ParamActionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_pkg::ParamActionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_pkg::ParamActionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_pkg::ParamActionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_pkg::ParamActionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_pkg::ParamActionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_pkg::ParamActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::hello_pkg::ParamActionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_pkg::ParamActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_pkg/ParamActionResponse";
  }

  static const char* value(const ::hello_pkg::ParamActionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_pkg::ParamActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool    success\n"
;
  }

  static const char* value(const ::hello_pkg::ParamActionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_pkg::ParamActionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParamActionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_pkg::ParamActionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_pkg::ParamActionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_PKG_MESSAGE_PARAMACTIONRESPONSE_H
